import { describe, expect, it, vi } from 'vitest';
import { createAgentTools } from '../src/agent-tools.js';
import type { CommandProject, ManagedCommandInput } from '../src/managed-commands.js';
const input:ManagedCommandInput={id:'call-1',text:'GH 법령 개정이력 진행상황',source:'terminal',userId:'owner'};
const project=(id:string,path=`/projects/${id}`,enabled=true):CommandProject=>({id,name:id,absolutePath:path,enabled,aliases:['alias-'+id],sensitivePaths:[],setupPolicy:'inherit'});
function setup(projects=[project('gh'),project('scsms')]) {
 const catalog={list:vi.fn(async()=>projects),resolve:vi.fn(async(id:string)=>{const p=projects.find(p=>p.id===id);if(!p)throw Error('missing');return p;}),add:vi.fn(),alias:vi.fn(),setEnabled:vi.fn()};
 const invoke=vi.fn(async(args:string[]):Promise<unknown>=>({ok:true,result:args[0]==='worktree'?{worktrees:projects.map(p=>({id:p.id+'::'+p.absolutePath,repoId:p.id,path:p.absolutePath,displayName:'GH 법령'}))}:args[0]==='project'?{setups:[]}:{terminals:[]}}));
 const execute=vi.fn(async(_i:ManagedCommandInput)=>({text:'ok',jobId:'j1',projectId:'gh'}));
 const locations={search:vi.fn(async()=>({paths:['/projects/new'],truncated:false})),create:vi.fn()};
 return {catalog,invoke,execute,locations,tools:createAgentTools({catalog,invoke,execute,locations})};
}
describe('Codex Orca tools',()=>{
 it('returns actual project identifiers and investigates multiple workspaces before selection',async()=>{const s=setup();expect(await s.tools.call('orca_projects',{},input)).toMatchObject({projects:[{id:'gh',aliases:['alias-gh']},{id:'scsms'}]});expect(await s.tools.call('orca_workspaces',{},input)).toMatchObject({workspaces:[{repoId:'gh'},{repoId:'scsms'}]});});
 it('rejects unknown arguments, shell escape surfaces and excluded native scopes',async()=>{const s=setup([project('off','/projects/off',false)]);await expect(s.tools.call('orca_workspaces',{repo:'off'},input)).rejects.toThrow();await expect(s.tools.call('orca_projects',{argv:['terminal','send']},input)).rejects.toThrow();await expect(s.tools.call('orca_execute',{action:'projects.add',path:'/projects/new'},input)).rejects.toThrow();expect(s.invoke).not.toHaveBeenCalled();expect(s.execute).not.toHaveBeenCalled();});
 it('only returns a registration/create proposal and never performs it',async()=>{const s=setup();expect(await s.tools.call('request_project',{mode:'create',path:'/projects/new',summary:'새 프로젝트'},input)).toEqual({proposal:{mode:'create',path:'/projects/new',summary:'새 프로젝트'}});expect(s.locations.create).not.toHaveBeenCalled();expect(s.catalog.add).not.toHaveBeenCalled();});
 it('passes validated actions and unique caller request identity to the existing relay',async()=>{const s=setup();await s.tools.call('orca_execute',{action:'jobs.run',project:'gh',prompt:input.text},input);expect(s.execute).toHaveBeenCalledWith({...input,text:'/hq '+JSON.stringify({action:'jobs.run',project:'gh',prompt:input.text})});});
 it('requires observed handles, bounds terminal reads, redacts secrets and blocks all HQ checkouts',async()=>{const s=setup([project('gh'),project('hq','/Users/me/orca/workspaces/orca-hq/feature')]);s.invoke.mockImplementation(async args=>({ok:true,result:args[0]==='worktree'?{worktrees:(await s.catalog.list()).map(p=>({id:p.id+'::'+p.absolutePath,repoId:p.id,path:p.absolutePath}))}:args[0]==='project'?{setups:[]}:args[1]==='list'?{terminals:[{handle:args[3]?.includes('hq')?'term-hq':'term-gh',preview:'PRIVATE PREVIEW'}]}:{text:'token=abc123 password=secret'}}));await expect(s.tools.call('orca_terminal_read',{handle:'term-gh'},input)).rejects.toThrow();await s.tools.call('orca_workspaces',{},input);await s.tools.call('orca_terminals',{workspace:'gh::/projects/gh'},input);expect(JSON.stringify(await s.tools.call('orca_terminal_read',{handle:'term-gh',limit:20},input))).not.toContain('abc123');await expect(s.tools.call('orca_terminal_read',{handle:'term-gh',limit:10000},input)).rejects.toThrow();await s.tools.call('orca_terminals',{workspace:'hq::/Users/me/orca/workspaces/orca-hq/feature'},input);await expect(s.tools.call('orca_terminal_read',{handle:'term-hq'},input)).rejects.toThrow();expect(s.invoke.mock.calls.filter(([a])=>a[1]==='read')).toHaveLength(1);});
 it('exposes registered folder contexts by name while hiding excluded and unrelated folders',async()=>{const s=setup([project('folder','/company/GH'),project('off','/company/off',false)]);s.invoke.mockImplementation(async args=>({ok:true,result:args[0]==='worktree'?{worktrees:[]}:{setups:[{id:'folder',repoId:'folder',kind:'folder',path:'/company/GH',displayName:'GH 법령 개정이력'},{id:'off',repoId:'off',kind:'folder',path:'/company/off'},{id:'other',kind:'folder',path:'/unrelated'}]}}));expect(await s.tools.call('orca_workspaces',{},input)).toMatchObject({folders:[{id:'folder:folder',displayName:'GH 법령 개정이력'}]});});
 it('scopes native runs and tasks by observed coordinator terminals and isolates sessions',async()=>{const s=setup();s.invoke.mockImplementation(async args=>({ok:true,result:args[0]==='worktree'?{worktrees:[{id:'gh::/projects/gh',repoId:'gh',path:'/projects/gh'}]}:args[0]==='project'?{setups:[]}:args[0]==='terminal'?{terminals:[{handle:'term-gh'}]}:args[1]==='run-list'?{runs:[{id:'run-gh',coordinator_handle:'term-gh',objective:'법령 개정이력'},{id:'run-other',coordinator_handle:'term-other'}]}:{tasks:[{id:'task-1',run_id:'run-gh',spec:'password=hidden'}]}}));expect(await s.tools.call('orca_runs',{repo:'gh'},input)).toMatchObject({runs:[{id:'run-gh',projectId:'gh'}]});expect(JSON.stringify(await s.tools.call('orca_tasks',{runId:'run-gh'},input))).not.toContain('hidden');await s.tools.call('orca_tasks',{runId:'run-gh',taskId:'task-1'},input);expect(s.invoke.mock.calls.at(-1)?.[0]).toEqual(['orchestration','task-list','--run','run-gh','--json']);await expect(s.tools.call('orca_tasks',{runId:'run-other'},input)).rejects.toThrow();await expect(s.tools.call('orca_tasks',{runId:'run-gh'},{...input,userId:'other'})).rejects.toThrow();s.catalog.resolve.mockResolvedValue(project('gh','/projects/gh',false));await expect(s.tools.call('orca_tasks',{runId:'run-gh'},input)).rejects.toThrow();});
 it('passes an observed full native workspace ID to relay, rejecting a different project',async()=>{const s=setup();await s.tools.call('orca_workspaces',{},input);await s.tools.call('orca_execute',{action:'jobs.run',project:'gh',worktree:'gh::/projects/gh',prompt:'검토'},input);expect(s.execute.mock.calls[0]?.[0].text).toContain('gh::/projects/gh');await expect(s.tools.call('orca_execute',{action:'jobs.run',project:'scsms',worktree:'gh::/projects/gh',prompt:'검토'},input)).rejects.toThrow();});

 it('discovers real GH/SCSMS sidebar folder contexts from ps and joins global terminals without previews',async()=>{
  const s=setup([project('gh-front','/projects/GH/front'),project('gh-back','/projects/GH/back'),project('scsms','/projects/GH-SCSMS/front')]);
  s.invoke.mockImplementation(async a=>({ok:true,result:a[0]==='project'?{setups:[]}:a[0]==='worktree'&&a[1]==='list'?{worktrees:[]}:a[0]==='worktree'?{worktrees:[{workspaceKind:'folder-workspace',worktreeId:'folder:gh',repoId:'folder-workspace:group-gh',path:'/projects/GH',displayName:'GH workspace',preview:'RAW PS',agents:[{prompt:'PRIVATE PROMPT'}]},{workspaceKind:'folder-workspace',worktreeId:'folder:scsms',path:'/projects/GH-SCSMS',displayName:'GH-SCSMS workspace'}]}:{terminals:[{handle:'term-law',worktreeId:'folder:gh',title:'법령개정이력 화면기획 비교분석 검토',preview:'RAW TERMINAL'},{handle:'term-scsms',worktreeId:'folder:scsms',title:'SCSMS'}]}}));
  const discovery=await s.tools.call('orca_workspaces',{},input);expect(discovery).toMatchObject({folders:[{id:'folder:gh',projectIds:['gh-front','gh-back']},{id:'folder:scsms',projectIds:['scsms']}]});expect(JSON.stringify(discovery)).not.toContain('RAW PS');expect(JSON.stringify(discovery)).not.toContain('PRIVATE PROMPT');
  const terminals=await s.tools.call('orca_terminals',{workspace:'folder:gh'},input);expect(terminals).toMatchObject({terminals:[{handle:'term-law',title:'법령개정이력 화면기획 비교분석 검토',rawReadable:true}]});expect(JSON.stringify(terminals)).not.toContain('term-scsms');expect(JSON.stringify(terminals)).not.toContain('RAW TERMINAL');expect(s.invoke.mock.calls.at(-1)?.[0]).toEqual(['terminal','list','--limit','100','--json']);
 });
 it('denies raw folder output if any nested project is excluded and rejects oversized proposals',async()=>{
  const s=setup([project('gh-front','/projects/GH/front'),project('off','/projects/GH/back',false)]);
  s.invoke.mockImplementation(async a=>({ok:true,result:a[0]==='project'?{setups:[]}:a[0]==='worktree'&&a[1]==='list'?{worktrees:[]}:a[0]==='worktree'?{worktrees:[{workspaceKind:'folder-workspace',worktreeId:'folder:gh',path:'/projects/GH'}]}:{terminals:[{handle:'term-law',worktreeId:'folder:gh'}]}}));
  await s.tools.call('orca_workspaces',{repo:'gh-front'},input);expect(await s.tools.call('orca_terminals',{workspace:'folder:gh'},input)).toMatchObject({terminals:[{rawReadable:false}]});await expect(s.tools.call('orca_terminal_read',{handle:'term-law'},input)).rejects.toThrow();expect(s.invoke.mock.calls.some(([a])=>a[1]==='read')).toBe(false);
  await expect(s.tools.call('request_project',{mode:'create',path:'/projects/new',summary:'x'.repeat(2001)},input)).rejects.toThrow();
 });

});

it('reads the native result.terminal envelope including cursor metadata',async()=>{
 const s=setup();s.invoke.mockImplementation(async a=>({ok:true,result:a[0]==='worktree'?{worktrees:[{id:'gh::/projects/gh',repoId:'gh',path:'/projects/gh'}]}:a[0]==='project'?{setups:[]}:a[1]==='list'?{terminals:[{handle:'term-law'}]}:{terminal:{handle:'term-law',tail:['법령 화면 구현 완료, 테스트 대기'],nextCursor:42,latestCursor:90,limited:true}}}));
 await s.tools.call('orca_workspaces',{},input);await s.tools.call('orca_terminals',{workspace:'gh::/projects/gh'},input);expect(await s.tools.call('orca_terminal_read',{handle:'term-law'},input)).toMatchObject({tail:['법령 화면 구현 완료, 테스트 대기'],nextCursor:42,limited:true});
});
it('blocks native task details and run objectives for a folder containing excluded projects',async()=>{
 const s=setup([project('front','/projects/GH/front'),project('off','/projects/GH/back',false)]);
 s.invoke.mockImplementation(async a=>({ok:true,result:a[0]==='project'?{setups:[]}:a[0]==='worktree'&&a[1]==='list'?{worktrees:[]}:a[0]==='worktree'?{worktrees:[{workspaceKind:'folder-workspace',worktreeId:'folder:gh',path:'/projects/GH'}]}:a[0]==='terminal'?{terminals:[{handle:'term-law',worktreeId:'folder:gh'}]}:a[1]==='run-list'?{runs:[{id:'run-gh',coordinator_handle:'term-law',objective:'EXCLUDED CONTENT'}]}:{tasks:[{id:'task-law',spec:'EXCLUDED CONTENT'}]}}));
 const runs=await s.tools.call('orca_runs',{},input);expect(JSON.stringify(runs)).not.toContain('EXCLUDED CONTENT');await expect(s.tools.call('orca_tasks',{runId:'run-gh'},input)).rejects.toThrow();await expect(s.tools.call('orca_runs',{runId:'run-gh'},input)).rejects.toThrow();expect(s.invoke.mock.calls.some(([a])=>a[1]==='task-list'||a[1]==='run-show')).toBe(false);
});
