import { createServer } from 'node:http';
import { chmod, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { openDatabase } from '@orca-hq/persistence';
import { collectLocalFacts, type ProjectFact } from './local-facts.js';
import { LocalTextStore, type LocalTextMessage } from './local-store.js';

export interface LocalChannels {
  start(): Promise<void>; stop(): Promise<void>;
  send(message: LocalTextMessage, text: string): Promise<void>;
  status(): { slack: boolean; telegram: boolean };
}
export type LocalChannelFactory = (ports: {
  onMessage(message: LocalTextMessage): Promise<void>;
  cursor: { load(channel: 'slack' | 'telegram'): string | number | undefined; save(channel: 'slack' | 'telegram', value: string | number): void };
}) => LocalChannels;
export interface LocalTextServiceOptions {
  databasePath: string;
  projects: readonly { projectKey: string; absolutePath: string; allowedOperations: readonly string[] }[];
  channelFactory: LocalChannelFactory;
  summarize(input: { question: string; facts: unknown; workingDirectory: string; signal?: AbortSignal }): Promise<string>;
  facts?: (() => Promise<ProjectFact[]>) | undefined;
  port?: number;
}

/** Repository-owned L0 runtime: no code edits, shell generated by a model, or dispatches. */
export async function startLocalTextService(options: LocalTextServiceOptions) {
  if (options.projects.length !== 5 || options.projects.some(p => p.allowedOperations.length !== 1 || p.allowedOperations[0] !== 'L0')) {
    throw new Error('local_text_requires_five_L0_projects');
  }
  const directory = dirname(options.databasePath);
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const workingDirectory = join(directory, 'text-summary-workspace');
  await mkdir(workingDirectory, { recursive: true, mode: 0o700 });
  const database = openDatabase(options.databasePath);
  try {
    await chmod(options.databasePath, 0o600);
    return await serveLocalText(options, database, workingDirectory);
  } catch (error) {
    if (database.open) database.close();
    throw error;
  }
}

async function serveLocalText(options: LocalTextServiceOptions, database: ReturnType<typeof openDatabase>, workingDirectory: string) {
  const store = new LocalTextStore(database);
  const abort = new AbortController();
  let started = false;
  let stopping = false;
  let active: Promise<void> | undefined;
  let timer: ReturnType<typeof setInterval> | undefined;
  const channels = options.channelFactory({
    onMessage: async (message) => {
      if (stopping) throw new Error('local_text_stopping');
      if (store.accept(message)) schedule();
    },
    cursor: { load: channel => store.loadCursor(channel), save: (channel, value) => store.saveCursor(channel, value) }
  });
  const server = createServer((request, response) => {
    const status = channels.status();
    const healthy = started && !stopping && status.slack && status.telegram;
    response.setHeader('Cache-Control', 'no-store');
    response.setHeader('X-Content-Type-Options', 'nosniff');
    if (request.method === 'GET' && request.url === '/health') {
      response.writeHead(healthy ? 200 : 503, { 'Content-Type': 'application/json' });
      response.end(JSON.stringify({ service: 'orca-hq', mode: 'text-only', state: healthy ? 'running' : 'degraded', pid: process.pid, channels: status, queue: store.summary() }));
    } else if (request.method === 'GET' && request.url === '/') {
      response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'" });
      response.end(`<!doctype html><html lang="ko"><meta charset="utf-8"><title>Orca HQ</title><style>body{font:18px system-ui;max-width:640px;margin:64px auto;padding:24px}p{line-height:1.7}</style><h1>Orca HQ</h1><p>${healthy ? '텍스트 조회 연결이 정상입니다.' : '연결 상태를 확인하고 있습니다.'}</p><p>Slack: ${status.slack ? '연결됨' : '연결 안 됨'}<br>Telegram: ${status.telegram ? '연결됨' : '연결 안 됨'}</p><p>등록한 5개 프로젝트의 상태를 Slack 또는 Telegram에서 질문하세요. 현재 모드는 조회 전용이며 파일 수정·커밋·배포와 음성 입력은 지원하지 않습니다.</p></html>`);
    } else { response.writeHead(404); response.end(); }
  });
  server.requestTimeout = 5000;
  server.headersTimeout = 5000;
  server.keepAliveTimeout = 1000;

  async function processQueue(): Promise<void> {
    while (!stopping) {
      const work = store.claim(Date.now());
      if (work === undefined) return;
      try {
        let response = work.response;
        if (response === undefined) {
          response = /^\/(?:start|help)(?:@\w+)?\s*$/u.test(work.message.text)
            ? 'Orca HQ 텍스트 조회 모드입니다. 예: “subway-seet 현재 브랜치와 변경 파일 수를 요약해줘”. 파일 수정·커밋·배포와 음성 입력은 실행하지 않습니다.'
            : await options.summarize({ question: work.message.text, facts: await (options.facts?.() ?? collectLocalFacts(options.projects)), workingDirectory, signal: abort.signal });
          if (stopping) return;
          store.saveResponse(work.message.id, response);
        }
        if (stopping) return;
        await channels.send(work.message, response);
        store.delivered(work.message.id);
      } catch {
        if (stopping) return;
        store.retry(work.message.id, Date.now() + Math.min(60000, 1000 * 2 ** work.attempts));
        process.stderr.write('Orca HQ: 텍스트 요청 처리 또는 응답 전송 재시도 예정.\n');
      }
    }
  }
  function schedule(): void {
    if (!started || stopping || active !== undefined) return;
    active = processQueue().catch(() => {
      process.stderr.write('Orca HQ: 텍스트 대기열 처리 실패.\n');
    }).finally(() => { active = undefined; });
  }
  let closed = false;
  async function stop(): Promise<void> {
    if (closed) return;
    closed = true;
    stopping = true;
    abort.abort();
    if (timer !== undefined) clearInterval(timer);
    await channels.stop().catch(() => undefined);
    await active;
    if (server.listening) await new Promise<void>(resolve => server.close(() => resolve()));
    database.pragma('wal_checkpoint(TRUNCATE)');
    database.close();
    closed = true;
  }
  try {
    await new Promise<void>((resolve, reject) => {
      server.once('error', reject);
      server.listen(options.port ?? 4310, '127.0.0.1', () => { server.removeListener('error', reject); resolve(); });
    });
    // Only the process holding the listener may recover the queue.
    store.recover();
    await channels.start();
    started = true;
    timer = setInterval(schedule, 250);
    schedule();
    const address = server.address();
    if (address === null || typeof address === 'string') throw new Error('local_text_listener_unavailable');
    return { port: address.port, stop, status: () => ({ channels: channels.status(), queue: store.summary() }) };
  } catch {
    await stop();
    throw new Error('local_text_start_failed');
  }
}
